// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostsModule.Infrastructure;

#nullable disable

namespace PostsModule.Migrations
{
    [DbContext(typeof(PostsContext))]
    [Migration("20250626085227_DeletionJobsAdded")]
    partial class DeletionJobsAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostsModule.Infrastructure.DeletePostJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("ImagesDeletionCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("PostDeletedEventPublished")
                        .HasColumnType("boolean");

                    b.Property<bool>("ThumbnailRemovedCompleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("DeletionJobs", "PostModule");
                });

            modelBuilder.Entity("PostsModule.Infrastructure.ImageEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Image", "PostModule");
                });

            modelBuilder.Entity("PostsModule.Infrastructure.PostEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryColor")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Posts", "PostModule");
                });

            modelBuilder.Entity("PostsModule.Infrastructure.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", "PostModule");
                });

            modelBuilder.Entity("PostsModule.Infrastructure.ImageEntity", b =>
                {
                    b.HasOne("PostsModule.Infrastructure.PostEntity", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("PostsModule.Infrastructure.PostEntity", b =>
                {
                    b.HasOne("PostsModule.Infrastructure.UserEntity", "Creator")
                        .WithMany("Posts")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("PostsModule.Infrastructure.PostEntity", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("PostsModule.Infrastructure.UserEntity", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
